name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)
trigger:
  batch: true
  branches:
    include:
      - main
      - dev

pool: 'Default'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: DataBuild
    displayName: Build and Validation
    jobs: 
      - job: BuildValidate
        displayName: Build and Analyze
        steps:
          - checkout: self
            clean: true
            persistCredentials: true
          - task: oneLuckiDevJson2Variable@1
            displayName: Parse JsonConfig
            inputs:
              jsonFile: .azpipelines/variables.json
              shouldPrefixVariables: true
              variablePrefix: 'deploy'
          - task: UseGitVersion@5
            displayName: 'GitVersion Update'
            inputs:
              versionSpec: '5.x'
          - task: UseDotNet@2
            condition: ne(variables['Build.Reason'], 'PullRequest')
            displayName: Use .NET From Global for Project Build
            inputs:
              packageType: 'sdk'
              useGlobalJson: true
              performMultiLevelLookup: true
          - task: SonarQubePrepare@4
            displayName: Prep Work For SonarQube
            inputs:
              SonarQube: 'ACS SonarQube'
              scannerMode: 'MSBuild'
              projectKey: $(deploy.ServiceName)
              projectName: $(deploy.ServiceDescription)
              projectVersion: $(GitVersion.SemVer)
              extraProperties: |
                sonar.dependencyCheck.reportPath=$(Build.SourcesDirectory)/dependency-check-report.xml     
                sonar.dependencyCheck.htmlReportPath=$(Build.SourcesDirectory)/dependency-check-report.html
                sonar.cpd.exclusions=**/AssemblyInfo.cs,**/*.g.cs
                sonar.cs.vscoveragexml.reportsPaths=$(System.DefaultWorkingDirectory)/**/*.coveragexml
                sonar.cs.vstest.reportsPaths=$(System.DefaultWorkingDirectory)/**/*.trx
          - task: DotNetCoreCLI@2
            displayName: 'Nuget Restore App'
            inputs:
              command: 'restore'
              projects: '**/*.csproj'
              restoreArguments: '/p:Configuration=$(buildConfiguration)'
              feedsToUse: 'select'
              vstsFeed: 'cff2a9ad-1f18-4677-a1ff-1ba023a01235/d3047bb1-10e2-412a-84f3-17a07c8e0ae8'
              includeNuGetOrg: false
              noCache: true
              verbosityRestore: 'Normal'
          - task: DotNetCoreCLI@2
            displayName: 'Build App'
            inputs:
              command: 'build'
              projects: '**/*.csproj'
              arguments: '-c $(buildConfiguration) --no-restore /p:Version=$(GitVersion.NuGetVersion)'
          - task: SonarQubeAnalyze@4
            displayName: 'Run Code Analysis'
          - task: SonarQubePublish@4
            displayName: 'Publish Quality Gate Result'
            inputs:
              pollingTimeoutSec: '1500'
          - task: CopyFiles@2
            condition: ne(variables['Build.Reason'], 'PullRequest')
            inputs:
              SourceFolder: ''
              Contents: '**/*.nupkg'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
              OverWrite: true
              flattenFolders: true
          - task: PublishBuildArtifacts@1
            condition: ne(variables['Build.Reason'], 'PullRequest')
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
          - task: GitTag@5
            condition: ne(variables['Build.Reason'], 'PullRequest')
            inputs:
              workingdir: '$(SYSTEM.DEFAULTWORKINGDIRECTORY)'
              tagUser: 'Alfred Neequaye'
              tagEmail: 'aneequaye@acsghana.com'
              tag: 'v$(GitVersion.NuGetVersion)'
              forceTagCreation: true
            env:
              SYSTEM_ACCESSTOKEN: $(system.accesstoken)